# Generated by Django 5.2.9 on 2025-12-09 18:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_parent_father_mobile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_class', 'first_name', 'last_name'], 'verbose_name': 'Học sinh', 'verbose_name_plural': 'Học sinh'},
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang học'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Số nhập học'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Nam'), ('Female', 'Nữ'), ('Others', 'Khác')], max_length=10, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='student',
            name='joining_date',
            field=models.DateField(verbose_name='Ngày nhập học'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Họ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(max_length=15, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.parent', verbose_name='Phụ huynh'),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tôn giáo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, max_length=10, verbose_name='Khối'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Mã học sinh'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(blank=True, upload_to='students/', verbose_name='Ảnh học sinh'),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, unique=True, verbose_name='Tên lớp')),
                ('class_code', models.CharField(max_length=10, unique=True, verbose_name='Mã lớp')),
                ('grade_level', models.CharField(max_length=20, verbose_name='Khối')),
                ('capacity', models.IntegerField(default=30, verbose_name='Sĩ số tối đa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên chủ nhiệm')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Lớp học',
                'ordering': ['grade_level', 'class_name'],
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='student.class', verbose_name='Lớp học'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, unique=True, verbose_name='Tên môn học')),
                ('subject_code', models.CharField(max_length=10, unique=True, verbose_name='Mã môn học')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên')),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Môn học',
                'ordering': ['subject_name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('status', models.CharField(choices=[('Present', 'Có mặt'), ('Absent', 'Vắng mặt'), ('Late', 'Đi muộn'), ('Excused', 'Có phép')], default='Present', max_length=10, verbose_name='Trạng thái')),
                ('remarks', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='student.student', verbose_name='Học sinh')),
            ],
            options={
                'verbose_name': 'Điểm danh',
                'verbose_name_plural': 'Điểm danh',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('Quiz', 'Kiểm tra 15 phút'), ('Midterm', 'Giữa kỳ'), ('Final', 'Cuối kỳ'), ('Assignment', 'Bài tập')], max_length=50, verbose_name='Loại kiểm tra')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Điểm số')),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Điểm tối đa')),
                ('grade_letter', models.CharField(blank=True, choices=[('A+', 'A+ (90-100)'), ('A', 'A (80-89)'), ('B+', 'B+ (70-79)'), ('B', 'B (60-69)'), ('C+', 'C+ (50-59)'), ('C', 'C (40-49)'), ('D', 'D (30-39)'), ('F', 'F (0-29)')], max_length=2, verbose_name='Xếp loại')),
                ('exam_date', models.DateField(verbose_name='Ngày thi')),
                ('remarks', models.TextField(blank=True, verbose_name='Nhận xét')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='student.student', verbose_name='Học sinh')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='student.subject', verbose_name='Môn học')),
            ],
            options={
                'verbose_name': 'Điểm số',
                'verbose_name_plural': 'Điểm số',
                'ordering': ['-exam_date'],
                'unique_together': {('student', 'subject', 'exam_type', 'exam_date')},
            },
        ),
    ]
