# Generated by Django 5.2.9 on 2025-12-16 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, unique=True, verbose_name='Mã giáo viên')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('specialization', models.CharField(blank=True, max_length=100, verbose_name='Chuyên môn')),
                ('qualification', models.CharField(blank=True, max_length=100, verbose_name='Trình độ')),
                ('joining_date', models.DateField(blank=True, null=True, verbose_name='Ngày vào làm')),
                ('teacher_image', models.ImageField(blank=True, upload_to='teachers/', verbose_name='Ảnh giáo viên')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang làm việc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Giáo viên',
                'verbose_name_plural': 'Giáo viên',
                'ordering': ['teacher_id', 'user__first_name', 'user__last_name'],
            },
        ),
    ]
