# Generated by Django 5.2.9 on 2025-12-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_student_user_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_letter',
            field=models.CharField(blank=True, choices=[('A+', 'A+ (9.0-10.0)'), ('A', 'A (8.0-8.9)'), ('B+', 'B+ (7.0-7.9)'), ('B', 'B (6.0-6.9)'), ('C+', 'C+ (5.0-5.9)'), ('C', 'C (4.0-4.9)'), ('D', 'D (3.0-3.9)'), ('F', 'F (0.0-2.9)')], max_length=2, verbose_name='Xếp loại'),
        ),
    ]
