# Generated by Django 5.2.9 on 2025-12-17 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_update_grade_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian duyệt'),
        ),
        migrations.AddField(
            model_name='grade',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_grades', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt'),
        ),
        migrations.AddField(
            model_name='grade',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Đã được duyệt'),
        ),
    ]
