# Generated by Django 5.2.9 on 2026-05-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_grade_approved_at_grade_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_code',
            field=models.CharField(blank=True, max_length=12, verbose_name='Mã tự động'),
        ),
    ]
