# Generated by Django 5.2.9 on 2026-05-03 09:59

from django.db import migrations, models
from datetime import datetime


def populate_student_codes(apps, schema_editor):
    """
    Tạo student_code cho các bản ghi hiện có chưa có code
    """
    Student = apps.get_model('student', 'Student')
    current_year = datetime.now().year
    prefix = f"HS{current_year}"

    students = Student.objects.filter(student_code='').order_by('created_at')
    
    counter = 1
    for student in students:
        while True:
            formatted_number = f"{counter:04d}"
            student_code = f"{prefix}{formatted_number}"
            
            if not Student.objects.filter(student_code=student_code).exists():
                student.student_code = student_code
                student.save(update_fields=['student_code'])
                print(f"Updated student {student.id} with code {student_code}")
                break
            counter += 1
        counter += 1


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20260503_1656'),
    ]

    operations = [
        migrations.RunPython(populate_student_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Mã học sinh'),
        ),
    ]
