# Generated by Django 5.2.9 on 2026-05-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_populate_and_add_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='Mã tự động'),
        ),
    ]
