# Generated by Django 5.2.9 on 2026-05-03 10:04

from django.db import migrations


def update_student_code_format(apps, schema_editor):
    """
    Cập nhật format student_code từ HS2026XXXX thành HS26XXXX
    """
    Student = apps.get_model('student', 'Student')
    
    students = Student.objects.filter(student_code__startswith='HS2026')
    for student in students:
        # Thay thế HS2026 thành HS26
        new_code = student.student_code.replace('HS2026', 'HS26', 1)
        student.student_code = new_code
        student.save(update_fields=['student_code'])
        print(f"Updated {student.student_code} to {new_code}")


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_student_student_code'),
    ]

    operations = [
        migrations.RunPython(update_student_code_format, migrations.RunPython.noop),
    ]
