# Generated by Django 5.2.9 on 2026-05-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_update_student_code_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_number', models.CharField(max_length=50, unique=True, verbose_name='Số báo danh')),
                ('full_name', models.CharField(max_length=200, verbose_name='Họ và tên')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('previous_school', models.CharField(max_length=255, verbose_name='Trường THCS')),
                ('math_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Điểm Toán')),
                ('literature_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Điểm Văn')),
                ('english_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Điểm Anh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thí sinh tuyển sinh',
                'verbose_name_plural': 'Thí sinh tuyển sinh',
                'ordering': ['exam_number'],
            },
        ),
    ]
