# Generated by Django 5.1.1 on 2026-05-03 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_admissioncandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncandidate',
            name='assigned_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_candidates', to='student.class', verbose_name='Lớp phân chia'),
        ),
    ]
