# Generated by Django 5.2.9 on 2026-05-05 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_admissioncandidate_assigned_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Thứ Hai'), ('Tuesday', 'Thứ Ba'), ('Wednesday', 'Thứ Tư'), ('Thursday', 'Thứ Năm'), ('Friday', 'Thứ Sáu'), ('Saturday', 'Thứ Bảy'), ('Sunday', 'Chủ Nhật')], max_length=10, verbose_name='Ngày trong tuần')),
                ('period', models.CharField(choices=[('1', 'Tiết 1 (7:00-7:45)'), ('2', 'Tiết 2 (7:45-8:30)'), ('3', 'Tiết 3 (8:45-9:30)'), ('4', 'Tiết 4 (9:30-10:15)'), ('5', 'Tiết 5 (10:30-11:15)'), ('6', 'Tiết 6 (11:15-12:00)'), ('7', 'Tiết 7 (13:00-13:45)'), ('8', 'Tiết 8 (13:45-14:30)'), ('9', 'Tiết 9 (14:45-15:30)'), ('10', 'Tiết 10 (15:30-16:15)')], max_length=2, verbose_name='Tiết học')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Phòng học')),
                ('academic_year', models.CharField(default='2026-2027', max_length=20, verbose_name='Năm học')),
                ('semester', models.CharField(choices=[('1', 'Học kỳ I'), ('2', 'Học kỳ II')], default='1', max_length=10, verbose_name='Học kỳ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='student.class', verbose_name='Lớp học')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='student.subject', verbose_name='Môn học')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên')),
            ],
            options={
                'verbose_name': 'Thời khóa biểu',
                'verbose_name_plural': 'Thời khóa biểu',
                'ordering': ['day_of_week', 'period'],
                'unique_together': {('class_obj', 'day_of_week', 'period', 'academic_year', 'semester')},
            },
        ),
    ]
