# Generated by Django 5.2.9 on 2025-12-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='AszlvqjAHxaOD3SqUFtJdSMvamI8m07P', editable=False, max_length=32, unique=True),
        ),
    ]
