# Generated by Django 5.1.1 on 2026-01-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='bR586IUNnNnjY0qkW3pNGBqn5bJW9sj8', editable=False, max_length=32, unique=True),
        ),
    ]
