# Generated by Django 5.2.9 on 2026-05-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0007_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='eq3UzIe7sdbqss0yuzzf98jOapTWwYyW', editable=False, max_length=32, unique=True),
        ),
    ]
